CREATE TABLE IF NOT EXISTS "user"
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id                  varchar(255)         null,
    name_zh                     varchar(255)         not null,
    email                       varchar(255)         not null,
    created_at                  timestamp            null,
    updated_at                  timestamp            null,
    name_en                     varchar(255)         null,
    nickname                    varchar(255)         null,
    phone                       varchar(255)         null,
    role                        int        default 0 not null,
    token_tg                    int                  null,
    token_line                  int                  null,
    remember_token              varchar(255)         null,
    create_user                 bigint               null,
    modify_user                 bigint               null,
    department_level            varchar(255)         null,
    gender                      smallint             null,
    altitude_sickness           smallint             null,
    special_disease             varchar(255)         null,
    dietary_habit               smallint             null,
    favorite_foods              varchar(255)         null,
    allergic_foods              varchar(255)         null,
    hate_foods                  varchar(255)         null,
    emergency_contact_person    varchar(255)         null,
    emergency_contact_relation  varchar(255)         null,
    emergency_contact_phone     bigint               null,
    home_phone_number           bigint               null,
    home_address                varchar(255)         null,
    days_in_mountain            int        default 0 not null,
    times_climbed_mountain      int        default 0 not null,
    five_kilograms_running_time time                 null,
    join_the_club_time          timestamp            null,
    personal_id                 varchar(255)         null,
    guard                       smallint             null,
    has_long_experience         boolean default false null,
    has_river_experience        boolean default false null,
    login_method                varchar(255)         null,
    river_guard                 smallint   default 0 not null,
    birthday                    varchar(255)         null,
    constraint user_personal_id_unique
        unique (personal_id),
    constraint user_student_id_unique
        unique (student_id)
);

COMMENT ON COLUMN "user".student_id IS '學號';
COMMENT ON COLUMN "user".name_zh IS '中文名稱';
COMMENT ON COLUMN "user".email IS '電子信箱';
COMMENT ON COLUMN "user".name_en IS '英文名字';
COMMENT ON COLUMN "user".nickname IS '暱稱';
COMMENT ON COLUMN "user".phone IS '手機';
COMMENT ON COLUMN "user".role IS '角色';
COMMENT ON COLUMN "user".token_tg IS 'Telegram Token';
COMMENT ON COLUMN "user".token_line IS 'LINE Token';
COMMENT ON COLUMN "user".remember_token IS 'Remember Token';
COMMENT ON COLUMN "user".create_user IS '建立者 ID';
COMMENT ON COLUMN "user".modify_user IS '更新者 ID';
COMMENT ON COLUMN "user".department_level IS '系級';
COMMENT ON COLUMN "user".gender IS '性別 0：男, 1：女';
COMMENT ON COLUMN "user".altitude_sickness IS '高山症 0：沒有, 1：輕微, 2：嚴重';
COMMENT ON COLUMN "user".special_disease IS '特殊疾病(加說明)';
COMMENT ON COLUMN "user".dietary_habit IS '葷素食調查 0：葷, 1：素, 2：蛋奶素';
COMMENT ON COLUMN "user".favorite_foods IS '喜歡的食物們';
COMMENT ON COLUMN "user".allergic_foods IS '過敏的食物們';
COMMENT ON COLUMN "user".hate_foods IS '討厭的食物們';
COMMENT ON COLUMN "user".emergency_contact_person IS '緊急聯絡人';
COMMENT ON COLUMN "user".emergency_contact_relation IS '與緊急聯絡人關係';
COMMENT ON COLUMN "user".emergency_contact_phone IS '緊急聯絡電話';
COMMENT ON COLUMN "user".home_phone_number IS '家裡電話';
COMMENT ON COLUMN "user".home_address IS '家裡住址';
COMMENT ON COLUMN "user".days_in_mountain IS '在山上的天數';
COMMENT ON COLUMN "user".times_climbed_mountain IS '爬山的次數';
COMMENT ON COLUMN "user".five_kilograms_running_time IS '五公里跑步時間';
COMMENT ON COLUMN "user".join_the_club_time IS '加入登山社時間';
COMMENT ON COLUMN "user".personal_id IS '身分證字號';
COMMENT ON COLUMN "user".guard IS '0：非嚮導, 1：初嚮, 2：領嚮';
COMMENT ON COLUMN "user".has_long_experience IS '是否有長程經驗';
COMMENT ON COLUMN "user".has_river_experience IS '是否有溯溪經驗';
COMMENT ON COLUMN "user".login_method IS '登入方式';
COMMENT ON COLUMN "user".river_guard IS '0：非溪嚮, 1：溪嚮';
COMMENT ON COLUMN "user".birthday IS '生日';
