CREATE TABLE IF NOT EXISTS post (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     varchar(24) NOT NULL,
    type        int NOT NULL,
    pin         smallint NOT NULL DEFAULT 0,
    title       varchar(50) NOT NULL,
    content     text NOT NULL,
    expired_at  timestamp NOT NULL,
    created_at  timestamp,
    updated_at  timestamp,
    create_user bigint,
    modify_user bigint
);

-- Column comments
COMMENT ON COLUMN post.type IS '類型（0 = 隊伍, 1 ＝ 社課, 2 = 其他';
COMMENT ON COLUMN post.pin IS '是否置頂 (0 = 否, 1 = 是)';
COMMENT ON COLUMN post.title IS '標題';
COMMENT ON COLUMN post.content IS '內容';
COMMENT ON COLUMN post.expired_at IS '過期時間';
COMMENT ON COLUMN post.create_user IS '建立者 ID';
COMMENT ON COLUMN post.modify_user IS '更新者 ID';